---
title: "Question 2"
output: github_document
---
Part 1

Firstly, it is obvious to see that high-crime cities have an incentive to hire lots of cops, so when we just get data from a few differnet cities and run the regession of "Crime" on "Police", we can generally see there exits a relatively positive relationship between Crime and Police. But it doesn't really make sense because it only shows a correlation between these two variables, not a causality.

Secondly, it is a relatively rare occurrence to find an example where we get lots of police for reasons unrelated to crime.

Part 2

For the researchers from UPenn, they used the terrorism alert system. And they use the different colors of different locations, like orange, red and other colors. For example, Washington DC is an important city and is likely to be a terrorism target, so the alert lever goes to orange.

In this way, the extra police are put on the Mall and other parts to protect against terrorists.
Therefore, it is nothing to do with the crime.

In the first column in the chart, we can see that when there is only one variable used in the High Alert dummy location, in the high alert area, there is a negative correlation between Police and Crime. That means one unit of police increase in the high alert area, 7.316 unit of crime will decrease on the average level, and it is significant at 10% level.

In the second column in the chart, when we consider the ridership in Washington DC, we can see that when we take the ridership into consideration, there is not a huge difference in the correlation between crime and police. That means one unit of police increase in the high alert area, 6.046 unit of crime will decrease on the average level, and it is significant at 10% level.

Part 3

The mean reason they controlled the Metro ridership is to figure out whether there was less tourist in an orange alert day, when there were more police which were uncorrelated with the crime showing on the street.

They did that, because firstly, they figured out the street crime happened to be less in an orange alert day with more police on the street.

And they wanted to know whether it was because robbers were hiding in their rooms.
Then they checked the ridership levels on the Metro system, and found they actually were not diminished on high-terror days, so in this way, the number of victims was largely unchanged.

Part 4

In the first column, we can see the researchers conduct two interaction variables high alert x District 1, and high alert x other districts.

So we can see the model has dependent variable is the daily total number of crimes in D.C, and the independent variable high alert x District 1, high alert x other districts, lg(midday ridership)

In the model, we can see that if it is the District 1, then one unit change of high alert days, will help decrease 2.62 unit of crime on the average level.

Also, then the locations belong to the other districts, then one unit change of high alert days, will help decrease 0.571 crime concentration on the national mall on the average level. But the result is significant even on the 10% level.

In this way, we can generally say that in different areas in the same high alert days, the influence on the reduction of crime is relatively different.

In the third row, we can see that one percent of midday ridership increase, the crime will increase 2.477% on the average level. It could show that the amount of tourists has correlation and even causation with crime.